### ISSUE TITLE
Unify K8s and OpenShift RBAC definitions

### ISSUE THREAD

**Issue by Jiri-Kremser** [Jiri-Kremser/spark-operator#34]
Following rbac should work with both K8s and OpenShift

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-resources
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers", "services", "configmaps"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: spark-operator-edit-resources
roleRef:
  kind: Role
  name: edit-resources
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: spark-operator
```
