### ISSUE TITLE
wrong label on pod created as spark cluster

### ISSUE THREAD

**Issue by Jiri-Kremser** [Jiri-Kremser/spark-operator#55]
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
  creationTimestamp: 2018-07-12T15:18:24Z
  generateName: my-spark-cluster-2-w-
  labels:
    radanalytics.io/cluster: my-spark-cluster-2
    radanalytics.io/deployment: my-spark-cluster-2-w
    radanalytics.io/kind: app
    radanalytics.io/podType: worker
```
line
```
radanalytics.io/kind: app
```
doesn't seems to be correct.

This was created by
```
oc create -f examples/test/cluster-2.yaml
```
