### ISSUE TITLE
Add a param to downloads that would say if the whole image startup fails in case of failed wgets

### ISSUE THREAD

**Issue by Jiri-Kremser** [Jiri-Kremser/spark-operator#69]
currently the behavior is that if one of the init containers fails, it automatically fails whole pod startup... we currently use the `&&` for chaining the particular commands like `wget` and echo to config. It's probably ok to fail the pod startup if the data can't be download (fail fast), however it should be configurable, because the crashloop thing isn't nice from the UX perspective.

**Comment by Jiri-Kremser** [comment]
```
  downloadData:
  - url: https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.csv
    to: /tmp/
    required: true|false
    downloadTimeout: int (seconds)
```

`downloadTimeout` would also contribute to `initialDelaySeconds` for probes on spark pods
